import { IClientData } from "../types/client";

export const mockClients: IClientData[] = [
  {
    id: 20,
    name: "John Doe",
    type: "Individual",
    email: "johndoe@email.com",
    createdAt: "2023-05-15",
    updatedAt: "2023-06-20",
    status: "Active",
  },
  {
    id: 21,
    name: "Test Test",
    type: "Individual",
    email: "test@test.com",
    createdAt: "2023-07-10",
    updatedAt: "2023-07-15",
    status: "Active",
  },
  {
    id: 22,
    name: "Acme Corporation",
    type: "Company",
    email: "info@acme.com",
    createdAt: "2023-04-05",
    updatedAt: "2023-06-12",
    status: "Active",
  },
  {
    id: 23,
    name: "Jane Smith",
    type: "Individual",
    email: "janesmith@email.com",
    createdAt: "2023-06-18",
    updatedAt: "2023-07-01",
    status: "Inactive",
  },
  {
    id: 24,
    name: "Global Enterprises",
    type: "Company",
    email: "contact@globalent.com",
    createdAt: "2023-03-22",
    updatedAt: "2023-05-30",
    status: "Active",
  },
  {
    id: 25,
    name: "Robert Johnson",
    type: "Individual",
    email: "robert@email.com",
    createdAt: "2023-07-05",
    updatedAt: "2023-07-05",
    status: "Pending",
  },
  {
    id: 26,
    name: "Tech Solutions Inc",
    type: "Company",
    email: "support@techsolutions.com",
    createdAt: "2023-02-15",
    updatedAt: "2023-06-25",
    status: "Active",
  },
  {
    id: 27,
    name: "Emily Davis",
    type: "Individual",
    email: "emily@email.com",
    createdAt: "2023-06-30",
    updatedAt: "2023-07-02",
    status: "Active",
  },
];
